version: "3.9"

services:
  pi-stock-trader:
    build:
      context: https://github.com/ryo-wijaya/pi-stock-trader.git
      args:
        - --branch=main
    ports:
      - "8001:8001"
    container_name: pi-stock-trader

  pi-bus:
    build:
      context: https://github.com/ryo-wijaya/pi-bus.git
      args:
        - --branch=main
    ports:
      - "8002:8002"
    container_name: pi-bus

  my-pi-board:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    container_name: my-pi-board
